version: '3.9'
services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=chatdb
      - DB_USER=chatuser
      - DB_PASSWORD=chatpass
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ../django_project.log:/var/lib/postgresql/data/postgres.log
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_destination=stderr", "-c", "log_directory=/var/lib/postgresql/data", "-c", "log_filename=postgres.log", "-c", "log_statement=all"]
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  postgres_data:
